### ISSUE TITLE
Метрополитен 1

### ISSUE THREAD

**Issue by 21xxone** [21xxone/Dz_wasp#1]
Вроде как сделал, но не уверен что до конца правильно, критике только рад. (про комментарии знаю)

**Comment by vdetstvepil** [comment]
**Файл Line.cs**
- Почему методы GetStation и FindStationByName ничего не возвращают? Будет выдана ошибка компиляции. Пусть методы возвращают пустую ссылку.

**Файл Metro.cs**
- То же самое касается методов FindStation и GetStationList.

**Файл Station.cs**
- 28 строка. Если присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Принято, но жду исправлений!

**Comment by 21xxone** [comment]
@vdetstvepil Вроде как везде добавил null, как исправить список пока не понял

**Comment by vdetstvepil** [comment]
@21xxone ну смотри. Представь, что у тебя есть две переменных: 
```
Class obj1 = new Class();
Class obj2 = new Class();
```
Что будет, если сделать вот так?
`obj1 = obj2;`
А будет вот что. Ты присвоишь ссылку на obj2 первому объекту. И что бы ты не поменял у второго объекта, то же самое будет и у первого объекта. Что бы ты не поменял у первого объекта, изменения проявятся и во втором объекте. Т.е. ты первый объект заменил вторым, и на самом деле у тебя obj1 - это obj2. 
Тебе нужны две разных переменных, а не одна и та же. Со списками работает так же. Поэтому тебе нужно сделать цикл foreach по входному списку, чтобы добавить элементы из входного списка в основной список.

**Comment by 21xxone** [comment]
@vdetstvepil понял, исправил

**Comment by vdetstvepil** [comment]
Принято.
