### ISSUE TITLE
Автопарк

### ISSUE THREAD

**Issue by 21xxone** [21xxone/Dz_wasp#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- 19, 50, 85, 86 строка. Инициализацию переменных следует проводить в конструкторе.
- 90 и 91 строка. Как и в домашке с метрополитеном, у тебя аналогичная ошибка. Если ты присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Молодец 👍 поправь ошибки и зачту.

**Comment by 21xxone** [comment]
@vdetstvepil исправлено

**Comment by vdetstvepil** [comment]
Принято.
