### ISSUE TITLE
Wpf2

### ISSUE THREAD

**Issue by 21xxone** [21xxone/Dz_wasp#6]
@GalteXx

**Comment by 21xxone** [comment]
Wpf2_dz

**Comment by GalteXx** [comment]
Ты не забыл Click как event к кнопкам присвоить?

**Comment by 21xxone** [comment]
видимо забыл, да и вообще как работает забыл. Это на каком то уроке рассказывалось?

**Comment by 21xxone** [comment]
да, я думал в самом начале сделал, но нет.. @GalteXx

**Comment by 21xxone** [comment]
сейчас коммитну

**Comment by 21xxone** [comment]
@GalteXx не знаю, возможно не показало тогда..

**Comment by GalteXx** [comment]
Я думал что я тебе все проставил...
Сегодня вечером перепроверю

**Comment by GalteXx** [comment]
У тебя кнопки не меняют надписи при начале нажатия MouseDown

https://github.com/21xxone/Dz_wasp/blob/6e4d606e61fb083b6ac9e21777961f611cd78441/WpfApp2_dz/WpfApp1/MainWindow.xaml.cs#L46
Вот это вовсе не обязательно

У btnaccept ничего не присвоено к Click

 Допили и будет 2 стингера. Пока ни одного, т.к. нет обязательной части

**Comment by 21xxone** [comment]
@GalteXx Вроде сделал

**Comment by 21xxone** [comment]
@GalteXx я все сделал, кроме смещения полей вроде как
